name: build-lepmonos-arm64

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: yourorg/lepmonos

jobs:
  build-arm64:
    # Use ARM runner
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Setup Buildx for Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver: docker-container  # comments in English only

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ARM64 image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:arm64-latest
          cache-to: type=registry,mode=max,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-cache:arm64
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-cache:arm64
          build-args: |
            BUILD_DATE=${{ github.run_id }}
